services:

  server:
    build: .
    ports:
      - 8080:80
    volumes:
      - ./src/:/var/www/html/
    networks:
      - app_network

  db_mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes: 
      - ./datadir/mysql/:/var/lib/mysql/
    networks:
      - app_network
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: kp_esportes

  db_pgsql:
    image: postgres
    ports:
      - 5432:5432
    volumes: 
      - ./datadir/pgsql/:/var/lib/pgsql/
    networks:
      - app_network
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: kp_esportes
      POSTGRES_DB: kp_esportes

networks:
  
  app_network:
    driver: bridge